# Generated by Django 5.0.4 on 2024-04-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_cart_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_total_price',
            field=models.IntegerField(default=0),
        ),
    ]
